### ISSUE TITLE
Build failed in Ubuntu 14.04

### ISSUE THREAD

**Issue by Guokr1991** [IFL-CAMP/supra#43]
Hi, 
My computer configuration is Ubuntu 14.04 x86_64， cmake 3.4.0, gcc 4.8.4, QT>= 5.5, CUDA 8.0.
After i clone the master code, followed the build process, it comes to errors:
CMake Error at cmake/FindCUDA.cmake:1366 (string):
  string does not recognize sub-command APPEND
Call Stack (most recent call first):
  cmake/FindCUDA.cmake:1731 (CUDA_WRAP_SRCS)
  src/SupraLib/CMakeLists.txt:362 (CUDA_ADD_LIBRARY)

CMake Error at cmake/FindCUDA.cmake:1372 (string):
  string does not recognize sub-command APPEND
Call Stack (most recent call first):
  cmake/FindCUDA.cmake:1731 (CUDA_WRAP_SRCS)
  src/SupraLib/CMakeLists.txt:362 (CUDA_ADD_LIBRARY)

CMake Error at cmake/FindCUDA.cmake:1366 (string):
  string does not recognize sub-command APPEND
Call Stack (most recent call first):
  cmake/FindCUDA.cmake:1731 (CUDA_WRAP_SRCS)
  src/SupraLib/CMakeLists.txt:362 (CUDA_ADD_LIBRARY)

CMake Error at cmake/FindCUDA.cmake:1372 (string):
  string does not recognize sub-command APPEND
Call Stack (most recent call first):
  cmake/FindCUDA.cmake:1731 (CUDA_WRAP_SRCS)
  src/SupraLib/CMakeLists.txt:362 (CUDA_ADD_LIBRARY)

CMake Error at cmake/FindCUDA.cmake:1366 (string):
  string does not recognize sub-command APPEND
Call Stack (most recent call first):
  cmake/FindCUDA.cmake:1731 (CUDA_WRAP_SRCS)
  src/SupraLib/CMakeLists.txt:362 (CUDA_ADD_LIBRARY)

CMake Error at cmake/FindCUDA.cmake:1372 (string):
  string does not recognize sub-command APPEND
Call Stack (most recent call first):
  cmake/FindCUDA.cmake:1731 (CUDA_WRAP_SRCS)
  src/SupraLib/CMakeLists.txt:362 (CUDA_ADD_LIBRARY)

CMake Error at cmake/FindCUDA.cmake:1366 (string):
  string does not recognize sub-command APPEND
Call Stack (most recent call first):
  cmake/FindCUDA.cmake:1731 (CUDA_WRAP_SRCS)
  src/SupraLib/CMakeLists.txt:362 (CUDA_ADD_LIBRARY)

CMake Error at cmake/FindCUDA.cmake:1372 (string):
  string does not recognize sub-command APPEND
Call Stack (most recent call first):
  cmake/FindCUDA.cmake:1731 (CUDA_WRAP_SRCS)
  src/SupraLib/CMakeLists.txt:362 (CUDA_ADD_LIBRARY)

By searching the google, can not find the results. So, please help to solve this problem, thanks.

**Comment by goeblr** [comment]
I'm sorry, I cannot reproduce this. Our buildserver uses 3.4 for the 14.04 build and the build works.

Is there any chance you have several versions of cmake installed?
Could you provide the output of 
``cmake --version

**Comment by Guokr1991** [comment]
Yes, you are right. it is the cmake version that is lower than 3.4. Now, the problem has been solved. Thanks.
