### ISSUE TITLE
[Feature] Output image stream when for Rest API

### ISSUE THREAD

**Issue by waltsims** [IFL-CAMP/supra#90]

**Comment by goeblr** [comment]
@waltsims could you provide more details on that?

**Comment by waltsims** [comment]
@goeblr Maybe I missunderstood, but when using the Rest-API, how does one get an output of the processed frames? Is there a fmpeg stream or something similar?

**Comment by goeblr** [comment]
For now the REST interface is only an interface to the parameters / nodes.
For output you can use any of the output nodes, e.g. IGTL.

Adding a web video stream output node could be interesting.

Can you quickly outline how you would use it?

**Comment by waltsims** [comment]
using a remote device as the client for the REST-API I would configure the Supra-server. Then use visualize the live images on either the server or a separate client.

**Comment by goeblr** [comment]
And what kind of platform would the client (the one potentially receiving images) be?

If you are thinking of a browser as the client, the only option would be an http or rtmp based streaming server. This is possible to do, e.g. with libav, but its also somewhat cumbersome for the build. Additionally, you would get the increased processing load and especially latency for compression.

So if the client could use something else, that would make the situation easier. I think there night be a node.js / electron version of zmq :)

**Comment by goeblr** [comment]
Is this still a consideration? Otherwise I would close this issue.

**Comment by waltsims** [comment]
Still considering. Would make a lot of sense IMHO.
